import type { UserProfile, Contact } from './types';

export const userProfile: UserProfile = {
  id: 'usr-001',
  uid: 'usr-001',
  name: 'Rohan Sharma',
  role: 'Senior Developer',
  company: 'InfoSys',
  email: 'rohan.sharma@infosys.com',
  phone: '+91 98765 43210',
  website: 'infosys.com',
  avatarUrl: 'https://picsum.photos/seed/rohan/200/200',
  cardBackgroundUrl: '/card-bg-default.svg',
  cardTier: 'gold',
};

export const contacts: Contact[] = [
  {
    id: 'usr-002',
    uid: 'usr-002',
    name: 'Priya Patel',
    role: 'Frontend Developer',
    company: 'Tech Mahindra',
    email: 'p.patel@techmahindra.com',
    phone: '+91 91234 56789',
    website: 'techmahindra.com',
    avatarUrl: 'https://picsum.photos/seed/priya/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'bronze',
  },
  {
    id: 'usr-003',
    uid: 'usr-003',
    name: 'Amit Singh',
    role: 'Project Manager',
    company: 'Wipro',
    email: 'amit.s@wipro.com',
    phone: '+91 99887 76655',
    website: 'wipro.com',
    avatarUrl: 'https://picsum.photos/seed/amit/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'silver',
  },
  {
    id: 'usr-004',
    uid: 'usr-004',
    name: 'Sunita Gupta',
    role: 'UX Researcher',
    company: 'HCL Tech',
    email: 's.gupta@hcl.com',
    phone: '+91 92345 67890',
website: 'hcltech.com',
    avatarUrl: 'https://picsum.photos/seed/sunita/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'bronze',
  },
  {
    id: 'usr-005',
    uid: 'usr-005',
    name: 'Vikram Kumar',
    role: 'Data Scientist',
    company: 'Tata Consultancy',
    email: 'vikram.k@tcs.com',
    phone: '+91 93456 78901',
website: 'tcs.com',
    avatarUrl: 'https://picsum.photos/seed/vikram/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'diamond',
  },
    {
    id: 'usr-006',
    uid: 'usr-006',
    name: 'Anjali Mehta',
    role: 'Backend Engineer',
    company: 'LTIMindtree',
    email: 'a.mehta@ltimindtree.com',
    phone: '+91 94567 89012',
website: 'ltimindtree.com',
    avatarUrl: 'https://picsum.photos/seed/anjali/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'gold',
  },
  {
    id: 'usr-007',
    uid: 'usr-007',
    name: 'Deepak Reddy',
    role: 'DevOps Specialist',
    company: 'Persistent Systems',
    email: 'd.reddy@persistent.com',
    phone: '+91 95678 90123',
website: 'persistent.com',
    avatarUrl: 'https://picsum.photos/seed/deepak/200/200',
    cardBackgroundUrl: '/card-bg-default.svg',
    cardTier: 'silver',
  },
];
