import type { UserProfile, Contact } from './types';

export const userProfile: UserProfile = {
  id: 'usr-001',
  name: 'Alex Doe',
  role: 'Lead Designer',
  company: 'PixelPerfect Inc.',
  email: 'alex.doe@pixelperfect.inc',
  phone: '+1 (555) 123-4567',
  website: 'pixelperfect.inc',
  avatarUrl: 'https://picsum.photos/200/200',
  cardBackgroundUrl: '/card-bg-default.svg',
};

export const contacts: Contact[] = [
  {
    id: 'usr-002',
    name: 'Samantha Ray',
    role: 'Frontend Developer',
    company: 'CodeCrafters',
    email: 's.ray@codecrafters.dev',
    phone: '+1 (555) 234-5678',
    website: 'codecrafters.dev',
    avatarUrl: 'https://picsum.photos/201/201',
  },
  {
    id: 'usr-003',
    name: 'Ben Carter',
    role: 'Project Manager',
    company: 'Innovate Solutions',
    email: 'ben.c@innovatesol.com',
    phone: '+1 (555) 345-6789',
    website: 'innovatesol.com',
    avatarUrl: 'https://picsum.photos/202/202',
  },
  {
    id: 'usr-004',
    name: 'Maria Garcia',
    role: 'UX Researcher',
    company: 'UserFirst Labs',
    email: 'm.garcia@userfirst.io',
    phone: '+1 (555) 456-7890',
    website: 'userfirst.io',
    avatarUrl: 'https://picsum.photos/203/203',
  },
  {
    id: 'usr-005',
    name: 'Kenji Tanaka',
    role: 'Data Scientist',
    company: 'QuantumLeap AI',
    email: 'kenji.t@quantumleap.ai',
    phone: '+1 (555) 567-8901',
    website: 'quantumleap.ai',
    avatarUrl: 'https://picsum.photos/204/204',
  },
    {
    id: 'usr-006',
    name: 'Aisha Khan',
    role: 'Backend Engineer',
    company: 'DataStream',
    email: 'a.khan@datastream.co',
    phone: '+1 (555) 678-9012',
    website: 'datastream.co',
    avatarUrl: 'https://picsum.photos/205/205',
  },
  {
    id: 'usr-007',
    name: 'Leo Chen',
    role: 'DevOps Specialist',
    company: 'CloudNine',
    email: 'l.chen@cloudnine.com',
    phone: '+1 (555) 789-0123',
    website: 'cloudnine.com',
    avatarUrl: 'https://picsum.photos/206/206',
  },
];
