import type { UserProfile, Contact } from './types';

export const userProfile: UserProfile = {
  id: 'usr-001',
  name: 'Rohan Sharma',
  role: 'Senior Developer',
  company: 'InfoSys',
  email: 'rohan.sharma@infosys.com',
  phone: '+91 98765 43210',
  website: 'infosys.com',
  avatarUrl: 'https://picsum.photos/200/200',
  cardBackgroundUrl: '/card-bg-default.svg',
};

export const contacts: Contact[] = [
  {
    id: 'usr-002',
    name: 'Priya Patel',
    role: 'Frontend Developer',
    company: 'Tech Mahindra',
    email: 'p.patel@techmahindra.com',
    phone: '+91 91234 56789',
    website: 'techmahindra.com',
    avatarUrl: 'https://picsum.photos/201/201',
  },
  {
    id: 'usr-003',
    name: 'Amit Singh',
    role: 'Project Manager',
    company: 'Wipro',
    email: 'amit.s@wipro.com',
    phone: '+91 99887 76655',
    website: 'wipro.com',
    avatarUrl: 'https://picsum.photos/202/202',
  },
  {
    id: 'usr-004',
    name: 'Sunita Gupta',
    role: 'UX Researcher',
    company: 'HCL Tech',
    email: 's.gupta@hcl.com',
    phone: '+91 92345 67890',
    website: 'hcltech.com',
    avatarUrl: 'https://picsum.photos/203/203',
  },
  {
    id: 'usr-005',
    name: 'Vikram Kumar',
    role: 'Data Scientist',
    company: 'Tata Consultancy',
    email: 'vikram.k@tcs.com',
    phone: '+91 93456 78901',
    website: 'tcs.com',
    avatarUrl: 'https://picsum.photos/204/204',
  },
    {
    id: 'usr-006',
    name: 'Anjali Mehta',
    role: 'Backend Engineer',
    company: 'LTIMindtree',
    email: 'a.mehta@ltimindtree.com',
    phone: '+91 94567 89012',
    website: 'ltimindtree.com',
    avatarUrl: 'https://picsum.photos/205/205',
  },
  {
    id: 'usr-007',
    name: 'Deepak Reddy',
    role: 'DevOps Specialist',
    company: 'Persistent Systems',
    email: 'd.reddy@persistent.com',
    phone: '+91 95678 90123',
    website: 'persistent.com',
    avatarUrl: 'https://picsum.photos/206/206',
  },
];
